meta_product_name: "Nationall"
meta_title: "Nationall - News to break borders"
meta_description: "Nationall is a European newspaper written by locals"
meta_image: "meta_image"                       # should exist in `app/assets/images/`
twitter_account: "@_Nationall"
